---
abstract: 'paranoid dns resolver'
author:
  - 'Tokuhiro Matsuno < tokuhirom @A gmail DOT. com>'
build_requires:
  Test::More: 0.98
configure_requires:
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Module::Build version 0.4001, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-DNS-Paranoid
no_index:
  directory:
    - inc
provides:
  Net::DNS::Paranoid:
    file: lib/Net/DNS/Paranoid.pm
    version: 0.06
requires:
  Class::Accessor::Lite: 0.05
  Net::DNS: 0.68
  perl: 5.008008
resources:
  license: http://dev.perl.org/licenses/
version: 0.06
